### ISSUE TITLE
Add a native-assets healthcheck / doctor command (npx ... doctor)

### ISSUE THREAD

**Issue by eszlamczyk** [software-mansion-labs/react-native-enriched-markdown#750]
## Summary

Add a `doctor`-style healthcheck (invokable via `npx`) that reports whether the vendored native assets (RaTeX for iOS math, tree-sitter grammars for code highlighting) are actually present and match the pinned versions, and prints an actionable fix when they are not.

Low priority - a nice-to-have for supportability. We can circle back when there is time.

## Motivation

The vendored assets are gitignored and downloaded on the consumer's machine at postinstall (`ios/vendor` is excluded from the tarball, restored by `vendor-ratex.mjs` / `vendor-grammars.mjs`). When a download partially fails, the symptom surfaces far from the cause - most sharply in #745, where a half-vendored RaTeX tree turned into `ENRMRaTeXBridge.swift:18:25: error: cannot find type 'RaTeXRenderer' in scope` several hundred lines into a pod build, with no hint that a download was the problem.

The fix for #745 makes a failed download look like an absent one (no partial tree) and warns at install and build time. A healthcheck is the complementary, user-initiated diagnostic: "is my install actually complete, and if not, what do I run?"

## Proposed shape

- Add a `bin` to `package.json` (there is none today), e.g. `npx react-native-enriched-markdown doctor`.
- Reuse the existing `present(m, dir)` predicate + stamp/manifest comparison from `vendor-ratex.mjs` (and the equivalent in `vendor-grammars.mjs`) so the doctor's notion of "complete" is identical to the vendor scripts'.
- Read the app `package.json` `"enriched-markdown"` config (enableMath / enableCodeHighlight) and cross-check requested-vs-on-disk.
- Print a compact report: for each feature, requested? / assets on disk? / stamp matches the pin? / the exact command to fix (`node node_modules/react-native-enriched-markdown/postinstall.mjs`).
- Optionally, wire it into the postinstall failure summary so a failed install points at `... doctor`.

## Scope / non-goals

- Checks node_modules asset presence and pin match only; it does not run a pod/gradle build. That still covers the #745 class of failure (missing/partial vendored assets), which is the common support case.

## Related

- #745 (the bug that motivated this)
